### ISSUE TITLE
please explain the installation procces for me 

### ISSUE THREAD

**Issue by alwinsajip** [Briuor/wbm#11]
I am new in github. And I have'nt used these types of softwares or websites before.
Please help me to get out of this.
It will be so helpful if explained through a video

**Comment by Briuor** [comment]
**wbm** is a library for **nodeJS**, and like any library for nodeJS you install it using **npm(node package manager)**.
Steps:
- You must have nodeJS installed
- Open your terminal(on linux or windows), go to your project folder on the terminal
- Run this command: **npm install wbm**
- Create a anyname.js file
- Paste this example of code inside anyname.js(change the phone numbers inside the code to your phone before test, so you are gonna receive the messages)
```js
const wbm = require('wbm');

wbm.start().then(async () => {
    const phones = ['5535988841854', '35988841854', '5535988841854'];
    const message = 'Good Morning.';
    await wbm.send(phones, message);
    await wbm.end();
}).catch(err => console.log(err));
```
- run the command: **node anyname.js**

Other Way:
- Just download the github repository
- The repository have a file called test.js
- run this command(on the terminal inside the repository folder downloaded): **node test.js**

Your issue is about how to install wbm, but how to install a npm package, so i recommend you to search about it.

**Comment by alwinsajip** [comment]
Do I need to install npm or ado I have to clone the repository

**Comment by Briuor** [comment]
When you install nodeJS, it installs npm too.
Installing wbm using npm is a way, git clone is another one, you can choose one of them.
I'm sorry but i can't make a video about it :(, i suggest you to learn a little bit of node, how to install a npm package and how to use a terminal.
wbm is a free programming solution i created for hobby, maybe in the future i can create a friendly interface.

**Comment by alwinsajip** [comment]
ok thanks
