### ISSUE TITLE
Sessions

### ISSUE THREAD

**Issue by z-h-z-h** [Briuor/wbm#4]
It would be nice to be able to log in through QR once and then reuse the session.
A similar solution is used in [pedroslopez/whatsapp-web.js](https://github.com/pedroslopez/whatsapp-web.js)

It’s also good to be able to use multiple sessions at the same time.

Is this possible now?

**Comment by Briuor** [comment]
> It would be nice to be able to log in through QR once and then reuse the session.
> A similar solution is used in [pedroslopez/whatsapp-web.js]

Reuse user's session is a very nice feature to be implemented, **wbm** uses puppeteer library that already provide easy ways to store user's session, for sure it will be implemented in a future release(feel free to contribute if you want).

> It’s also good to be able to use multiple sessions at the same time.
> Is this possible now?

There are two cases:
#### Case 1 - Multiple sessions of the same whatsapp account
It isn't possible because whatsapp don't allow opening more than one session at the same account in https://web.whatsapp.com.
#### Case 2 - Multiple sessions of different whatsapp accounts
It's possible, but not now, **wbm** instantiate a browser in background and do all stuff in the https://web.whatsapp.com page, so to use multiple different sessions at the same time will be necessary to open an anonymous browser instance for each session(open several browsers in background have a processing cost).

**Comment by Briuor** [comment]
The session feature was implemented in the version **v1.1.9** (the way to use the library changed a little bit in this version too), now the user must scan the QR code once.

**Comment by darkane188** [comment]
> La función de sesión se implementó en la versión **v1.1.9** (la forma de usar la biblioteca también cambió un poco en esta versión), ahora el usuario debe escanear el código QR una vez.

hay un bug al recuperar la sesion despues de leer el qr code solo aparece autenticando
![image](https://user-images.githubusercontent.com/10376033/91761528-adb48000-eb9a-11ea-8b16-98b845d03250.png)

**Comment by Briuor** [comment]
Thank you man, it's happening because whatsapp web changed some html tags, i'm gonna fix it!

**Comment by Briuor** [comment]
I released the session fix. Can you test it again?

**Comment by Briuor** [comment]
Fixed!
